## 簡単なクラスの例

In [17]:
class HumanBeing(): #class："class"オブジェクトの定義。ここでは"HumanBeing"　
    def __init__(self,first_name,eye_color): #__init__で始まる関数はコンストラクタと呼ばれる。（self,変数1、変数2,...とする）
        self.first_name = first_name #first_nameというattributeに初期値を与える。
        self.eye_color = eye_color #eye_colorというattributeに初期値を与える。
        self.position = 0
    def walk_steps(self,steps): #メソッド。class内のメソッドは、引数の一つ目は必ずselfにする。
        self.position +=steps

In [19]:
Sandra = HumanBeing('Sandra','blue') #インスタンス化

In [20]:
Sandra.first_name #first_nameの値を呼び出し

'Sandra'

In [22]:
Sandra.position #positionの値を呼び出し

0

In [30]:
Sandra.walk_steps(5) #class内のメソッドを回している

In [31]:
Sandra.position #positionの値を呼び出し

15

## Object Oriented Programmingには様々なメリットがある

・自然な発想  
・シンプルでわかりやすいコード  
・コンパクトでユーザーフレンドリーなコード（numpyを使った行列表記など）  

・抽象化されたフレキシブルなコード  
・モジュール性。classの組み合わせで様々なことができる。
・継承。classの継承ができる。
など  
ここでは具体的な話はしていない。

## integer object

In [32]:
n=5

In [33]:
type(n)

int

In [35]:
n.numerator #attribute

5

In [37]:
n.bit_length() #２進法で表すために必要なビット数

3

In [38]:
n+n

10

In [39]:
2*n

10

In [41]:
n.__sizeof__() #nというオブジェクトが何バイト使用しているかを返す。

28

## list object

In [42]:
l = [1,2,3,4]

In [43]:
type(l)

list

In [44]:
l[0]

1

In [46]:
l.append(10)

In [49]:
l + l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [50]:
2 * l

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [51]:
sum(l)

20

In [52]:
l.__sizeof__()

104

## ndarray object

In [53]:
import numpy as np

In [56]:
a = np.arange(16).reshape((4,4)) #aというオブジェクトを、「0から15までの整数を4×4の行列にしたもの」としている。

In [57]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
type(a)

numpy.ndarray

In [60]:
a.nbytes #aが何バイト使用しているかを返す。

128

In [61]:
a.sum()

120

In [64]:
a.cumsum(axis=0) #↓方向の累積和

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]])

In [65]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [66]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [67]:
sum(a)

array([24, 28, 32, 36])

In [68]:
np.sum(a)

120

In [69]:
a.__sizeof__()

112

## DataFrame object

In [70]:
import pandas as pd

In [73]:
df = pd.DataFrame(a,columns=list('abcd')) #列名をa b c dとするデータフレームオブジェクトの作成。

In [74]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [75]:
type(df)

pandas.core.frame.DataFrame

In [79]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [86]:
df.sum() #引数にaxisを取ることで行方向・列方向への和を取ることが可能

a    24
b    28
c    32
d    36
dtype: int64

In [87]:
df.cumsum()

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [88]:
df+df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [89]:
2*df

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [90]:
np.sum(df)

a    24
b    28
c    32
d    36
dtype: int64

In [91]:
df.__sizeof__()

208

# basics of python classes

In [109]:
# FinancialInstrumentというクラスの定義（中身はpassのみで特に何も実行しない）

class FinancialInstrument(object):
    pass

In [103]:
fi = FinancialInstrument()

In [104]:
type(fi)

__main__.FinancialInstrument

In [105]:
fi

In [106]:
fi.__str__() #オブジェクトを文字列に変換して返す。

'<__main__.FinancialInstrument object at 0x1140ac7f0>'

In [107]:
fi.price=100

In [108]:
fi.price

100

In [110]:
"""
classを定義する際は、多くの場合__init__関数が必要。また、引数の一つ目は必ずselfにする。
__init__の中で、引数の初期値を与える。
ここで、__init__にその側にあるauthorは定数のような扱い。
"""

class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self,symbol,price):
        self.symbol = symbol
        self.price = price

In [111]:
FinancialInstrument.author

'Yves Hilpisch'

In [114]:
#FinancialInstrumentクラスのsymbol,priceに値を与える。

aapl = FinancialInstrument('AAPL',100)

In [113]:
aapl.symbol

'AAPL'

In [115]:
aapl.author #これは定数（のようなもの）なので変わらない。

'Yves Hilpisch'

In [117]:
aapl.price = 105

In [118]:
aapl.price

105

In [123]:
# classの中にメソッド（関数）を入れることも可能（ここではget,set）

class FinancialInstrument(object):
    author = 'Yves Hilpisch'
    def __init__(self,symbol,price):
        self.symbol = symbol
        self.__price = price
    def get_price(self):
        return self.__price
    def set_price(self,price):
        self.__price = price

In [124]:
fi = FinancialInstrument('AAPL',100)

In [125]:
fi.get_price()

100

In [131]:
fi.__price #attributeに直接アクセスすることはできない。

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [137]:
fi._FinancialInstrument__price #_(クラス名)を前につけると直接アクセスできる。

100

In [135]:
fi._FinancialInstrument__price = 105 #同様に、_(クラス名)を前につけると上書きも可能。

In [136]:
fi.set_price(100)

In [138]:
#PortfolioPositionクラスの定義。

class PortfolioPosition(object):
    def __init__(self,financial_instrument,position_size):
        self.position = financial_instrument
        self.__position_size = position_size
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self,position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * self.position.get_price()

In [139]:
pp = PortfolioPosition(fi,10)

In [140]:
pp.get_position_size() #class内のget_position_size関数を回している。

10

In [141]:
pp.get_position_value() #class内のget_position_value関数を回している。

1000

In [143]:
pp.position.get_price() #class内のposition→fiのget_priceを回す。ここでは100が返される。

100

In [145]:
pp.position.set_price(105) #上書き
pp.get_position_value()

1050

# python data model

In [146]:
# vector classの定義

class Vector(object):
    def __init__(self,x=0,y=0,z=0):
        self.x = x
        self.y = y
        self.z = z

In [147]:
v = Vector(1,2,3)

In [148]:
v

In [149]:
#上のVectorクラスに__repr__メソッドを施している。__repr__は__str__とほぼ同じ。文字列に変換。

class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [150]:
v = Vector(1,2,3)

In [151]:
v

Vector(1, 2, 3)

In [152]:
print(v)

Vector(1, 2, 3)


In [163]:
# Vectorクラス。　__abs__でベクトルのノルムを、__bool__で0か否かの判定をする。

class Vector(Vector):
    def __abs__(self):
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))

In [164]:
v = Vector(1,2,-1)

In [165]:
abs(v)

2.449489742783178

In [166]:
bool(v)

True

In [168]:
v =Vector() #何も入れないと初期値として設定したx=y=z=0になる。

In [169]:
v

Vector(0, 0, 0)

In [170]:
abs(v)

0.0

In [171]:
bool(v)

False

In [172]:
# + や * は、__add__や__mul__で定義できる。

class Vector(Vector):
    def __add__(self,other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x,y,z)
    
    def __mul__(self,scalar):
        return Vector(self.x * scalar, self.y * scalar, self.z * scalar)

In [173]:
v = Vector(1,2,3)

In [180]:
v + Vector(2,3,4)

Vector(3, 5, 7)

In [181]:
v * 2

Vector(2, 4, 6)

In [182]:
# 要素の数を返すlenも定義できる。

class Vector(Vector):
    def __len__(self):
        return 3 # Vectorクラスで返されるベクトルはすべて要素が3つだから。
    
    # getitemでは要素取得のルールをif,elifを使って書いている。
    def __getitem__(self,i):
        if i in [0,-3]:
            return self.x
        elif i in [1,-2]:
            return self.y
        elif i in [2,-1]:
            return self.z
        else:
            raise IndexError('Index out of range.')

In [183]:
v = Vector(1,2,3)

In [184]:
len(v)

3

In [185]:
v[0]

1

In [186]:
v[-2]

2

In [187]:
v[3]

IndexError: Index out of range.

In [197]:
 # 説明保留

class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [198]:
v = Vector(1,2,3)

In [199]:
for i in range(3):
    print(v[i])

1
2
3


In [200]:
for coordinate in v:
    print(coordinate)

1
2
3


### 以上を一つにまとめたVectorクラスがこちら

In [202]:
class Vector(Vector):
    def __init__(self,x=0,y=0,z=0):
        self.x = x
        self.y = y
        self.z = z
        
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x ** 2 + self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self,other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x,y,z)
    
    def __mul__(self,scalar):
        return Vector(self.x * scalar, self.y * scalar, self.z * scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self,i):
        if i in [0,-3]:
            return self.x
        elif i in [1,-2]:
            return self.y
        elif i in [2,-1]:
            return self.z
        else:
            raise IndexError('Index out of range.')
            
        def __iter__(self):
            for i in range(len(self)):
                yield self[i]

In [203]:
v = Vector(3,1,4)

In [204]:
v.__abs__()

5.0990195135927845

## 練習問題

### ある数のリストが与えられた時に、リストから足して0になる2数の組み合わせを返すアルゴリズムをclassを使って組んでみましょう。
### 3つの場合もやってみましょう。
### また、2数のアルゴリズムと3数のアルゴリズムが格納されたクラスを作ってみましょう。

### 2数の場合の例　[4,9,-4,1,-9,3,6] → [-9,9] [-4,4]

### 3数の場合の例　[4,8,-10,-12,2,-3,-7] →[-12, 2, 10], [-12, 4, 8], [-10, 2, 8], [-7, -3, 10]